### ISSUE TITLE
Error in @google-cloud/firestore compatibility example

### ISSUE THREAD

**Issue by edonosotti** [Upstatement/firestore-jest-mock#112]
# Description

In the **@google-cloud/firestore compatibility** example:

`expect(userDocs[0].name).toEqual('Homer Simpson');`

fails with:

```
● testing stuff

    expect(received).toEqual(expected) // deep equality

    Expected: "Homer Simpson"
    Received: undefined

      25 |         console.error(userDocs);
      26 |         expect(mockCollection).toHaveBeenCalledWith("users");
    > 27 |         expect(userDocs.docs[0].name).toEqual("Homer Simpson");
         |                                       ^
      28 |       });
      29 | });
      30 |
```

## Solution

Change to:

`expect(userDocs.docs[0].data().name).toEqual("Homer Simpson");`

or get all docs first, via `map()`:

```
const result = userDocs.docs.map((doc) => doc.data());
```

**Comment by sbatson5** [comment]
Good catch! @edonosotti Did you want to open a PR to fix this?  I'm happy to tackle it otherwise

**Comment by edonosotti** [comment]
> Good catch! @edonosotti Did you want to open a PR to fix this? I'm happy to tackle it otherwise

Hi Scott, I thought of it, but somehow opening a PR to fix a line in the README felt a little unnecessary :)
I can do it if you prefer that, anyway, just let me know.

**Comment by sbatson5** [comment]
I wouldn't consider it unnecessary at all. All contributions (big and small) are welcome

**Comment by edonosotti** [comment]
Ok then, I will open the PR. Thanks!
