### ISSUE TITLE
Module firebase-admin not found, mocking skipped 

### ISSUE THREAD

**Issue by MorenoMdz** [Upstatement/firestore-jest-mock#115]
# Summary

I am trying to set up the `mockFirebase` in our expo project, however, I get the error:

```
    console.info
      Module firebase-admin not found, mocking skipped.

      at mockModuleIfFound (node_modules/firestore-jest-mock/mocks/firebase.js:49:13)
```     

Before opening an issue, do I need to install the firebase-admin to be able to use this library in the client?

Installing the firebase admin does make the mocking work, but is it really required? Also, do I need to import firebase twice, on top to init the app, and inside the test block as well, any ideas about what is wrong here?

![image](https://user-images.githubusercontent.com/29472480/126235353-bf7da6ca-2f4c-4ec0-acf5-7c973f365c74.png)

**Comment by sbatson5** [comment]
No, you don't need `firebase-admin`.  We just added those info logs (they aren't errors) in case people weren't aware why something wasn't getting mocked.

If you write a `describe` block that wraps everything, does it work?

```javascript
describe('Wrapping', () => {
 mockFirebase({ database: mockedFirestore, currentUser: 'mortysux@gmail.com' });

  beforeAll(() => { ... });

  describe('Overlapping shifts tests', () => { ... });
});
```

**Comment by bhr** [comment]
I needed to use `mockGoogleCloudFirestore` so firebase-admin Firestore is mocked.
