### ISSUE TITLE
Checking for mockUpdate within a datasnapshot forEach

### ISSUE THREAD

**Issue by kenchambers** [Upstatement/firestore-jest-mock#136]
# Summary

Is it possible to check if `mockUpdate` was called on a document that is inside of a `dataSnapshot.forEach`?

```js

// function i am testing: 

...
dataSnapshot.forEach((doc) => {

doc.update({param: 1})
})
...
```

But when i test using: 

```js
expect(mockCollection).toHaveBeenCalledWith('deals');
expect(mockUpdate).toHaveBeenCalled();
```

`mockCollection` is passing, but `mockUpdate` is not

**Comment by sbatson5** [comment]
Unfortunately, that is not currently possible. But it should! The docs returned by the snapshots right now are just basic objects and not mocks, but I definitely see the value in this

**Comment by kenchambers** [comment]
@sbatson5  I actually was able to get this to work. It also correctly reads the parameters passed into `doc.update`

**Comment by kenchambers** [comment]
thank you for your help
