### ISSUE TITLE
Fetch document with full path doesn't work

### ISSUE THREAD

**Issue by Philmod** [Upstatement/firestore-jest-mock#14]
# Description

When you fetch a specific document with full path, it doesn't find it from the mock database.

## Steps to reproduce

```
mockFirebase({
  database: {
    'mycol/id/mysubcol': [
      { id: 'subId' },
    ],
})

const doc = await lib.db
        .doc(`mycol/id/mysubcol/subId`)
        .get()
```

But this one does work: 

```
const doc = await lib.db
        .collection(`mycol/id/mysubcol`)
        .doc('subId')
        .get()
```

## Expected result

The document from the database.

## Actual result

No result.

## Environment

- OS: macos
- nodejs

**Comment by sbatson5** [comment]
Thanks for pointing this out. The mock DB makes the assumption that you would call `collection` first (as that's what I was doing in my repo) but it should definitely support what you're trying.  

Will take a look this week but PRs are definitely welcome too :)
