### ISSUE TITLE
Example of multiple tests with different database data?

### ISSUE THREAD

**Issue by Ravendarksky** [Upstatement/firestore-jest-mock#145]
Hello, firstly thank you for creating this wonderful library! I've been using it over the last week to write some very useful tests for my project.

I am not sure if this is a feature request, support question or bug!

I am wondering if there are any good examples of how to setup different database data for tests within one code file? I am finding that I have to use requires to import everything that uses firebase or else they get imported before the mocking happens and it doesn't work.

This seems to also mean that only the first mockGoogleCloudFirestore() is used within my tests.

Is there a way of storing an instance of mockGoogleCloudFirestore and adjusting the database? For now I am using mutable: true and managing the data between tests, but this is a lot of what feels unnecessary work.

Ideally I would also like to remove the need for using requires, as this is breaking my typescript and makes the tests harder to manage (if an imported file in tests starts using firebase then it has to be moved into a require or seemingly unrelated tests will start failing).

I am hoping that I am just missing something obvious here, but if not I would love a way of adjusting the data. I have provided a failing example test below:

```
import { mockGoogleCloudFirestore } from 'firestore-jest-mock';

describe('some tests', () => {
  it('Should do the first thing', async () => {
    mockGoogleCloudFirestore({
      database: {
        test: [{ id: '1', someField: true }],
      },
    });
    const { Firestore } = require('@google-cloud/firestore');
    const firestore = new Firestore();
    const results = await firestore.collection('test').get();
    expect(results.docs[0].data().someField).toEqual(true); // WORKS
  });

  it('Should do the second thing', async () => {
    mockGoogleCloudFirestore({
      database: {
        test: [{ id: '1', someField: false }],
      },
    });
    const { Firestore } = require('@google-cloud/firestore');
    const firestore = new Firestore();
    const results = await firestore.collection('test').get();
    expect(results.docs[0].data().someField).toEqual(false); // FAILS
  });
});
```

```
npm version: v8.12.1
Node version: v18.0.4
"firebase-functions-test": "2.4.0",
"@google-cloud/firestore": "6.0.0",
```

**Comment by Ravendarksky** [comment]
My other current workaround for this is to reset modules between tests, but this still means I have to require everything using firestore in the tests themselves after mockGoogleCloudFirestore has been run

 ```
 beforeEach(() => {
    jest.resetModules();
  });
```

**Comment by sbatson5** [comment]
Hey @Ravendarksky. Unfortunately, since `mockGoogleCloudFirestore` uses jest mocks, they get hoisted to the top of the file and executed with your imports (so they all run, but the run in succession before any test executes). This is a really annoying thing about jest mocks in general:
https://jestjs.io/docs/manual-mocks#using-with-es-module-imports

There isn't really a way to solve it without doing what you described. You can see a bit more about it here:
https://github.com/kentcdodds/how-jest-mocking-works

**Comment by sbatson5** [comment]
Closing as there has been no update. Feel free to reopen if my above answer doesn't help

**Comment by SimpleCreations** [comment]
Here's a solution I came up with that works without re-requiring `firebase-admin` before each test (useful for e2e testing).

#### In `setupFiles`
```ts
import { mockGoogleCloudFirestore } from 'firestore-jest-mock';

beforeAll(() => {
  let databaseMock: Record<PropertyKey, unknown> = {};

  globalThis.setFirestoreDatabaseMock = (
    value: Record<PropertyKey, unknown>,
  ) => {
    databaseMock = value;
  };

  globalThis.clearFirestoreDatabaseMock = () => {
    databaseMock = {};
  };

  mockGoogleCloudFirestore({
    database: new Proxy({}, { get: (_, prop) => databaseMock[prop] }),
  });
});
```

#### In a spec

```ts
afterEach(() => {
  clearFirestoreDatabaseMock();
});

describe('some tests', () => {
  it('Should do the first thing', async () => {
    setFirestoreDatabaseMock({
      test: [{ id: '1', someField: true }],
    });
    // Test something
  });

  it('Should do the second thing', async () => {
    setFirestoreDatabaseMock({
      test: [{ id: '2', someField: false }],
    });
    // Test something
  });
});
```
