### ISSUE TITLE
How does subcollection mocking work? Does it?

### ISSUE THREAD

**Issue by AverageHelper** [Upstatement/firestore-jest-mock#25]
# Summary
Now that `FakeFirestore.FieldValue` works, my unit tests can progress a little bit more.  I'm now running into trouble where subcollection access matters.

I have code that access the database like so:
```
const snap = await firestore
  .collection("accounts")
  .doc(accountId)
  .collection("userPermissions")
  .doc(userId)
  .get();
```
This returns a snapshot whose document doesn't exist. (That is, the object returned by the mock is simply `{ exists: false }`)  This needs to not be the case.

I have my firestore mock declared like so:
```
mockFirebase({
  database: {
    accounts: [ // Root-level collection
      { // A document
        id: "testAcct",
        conversations: [ // Subcollection, right?
          { id: "testConvo", participants: ["right-user", "admin-user"] },
        ],
        userPermissions: [ // Subcollection, right??
          { id: "right-user", level: "normal" },
          { id: "admin-user", level: "admin" },
          { id: "owner", level: "super" },
        ]
      },
    ]
  }
});
```
Am I missing something here?  Is this my bad, or does the package not yet support mocking subcollections?

## Relevant information
I should note that I see no mention in the package about subcollections, so I can only assume based on the root case that this is how subcollections are meant to be represented.

To further edge the point, I threw a test case on the package, which sadly fails:
```
const db = new FakeFirestore({
  characters: [
    { id: 'homer', name: 'Homer', occupation: 'technician' },
    { id: 'krusty', name: 'Krusty', occupation: 'clown' },
    { // I added this document only
      id: 'bob',
      name: 'Bob',
      occupation: 'repairman',
      family: [ // I see this as a subcollection.  Am I wrong, or is the mock?
        { id: 'thing1', name: 'Thing 1', relation: 'pet' },
        { id: 'thing2', name: 'Thing 2', relation: 'pet' },
        { id: 'deborah', name: 'Deborah', relation: 'wife' },
      ],
    },
  ],
});

test('it can fetch records from subcollections', async () => {
  expect.assertions(2);
  const record = await db
    .collection('characters')
    .doc('bob')
    .collection('family')
    .doc('thing1')
    .get();
  expect(record.exists).toBe(true);  // Expected: true, Received: false
  expect(record.data()).toHaveProperty('name', 'Thing 1');
});
```

### Environment (if relevant)
firestore-jest-mock 0.3.0

**Comment by AverageHelper** [comment]
Part of the bother appears to be this line here in `FakeFirestore.doc`:
```
const records = this.database[this.collectionName] || [];
```
We shouldn't always check in `this.database`. What if our present spot is a document? To avoid ambiguity between array members and subcollections, I recommend we look for a special key in the mock structure called `_subcollections`. This would map to an object with collection IDs and arrays of document children. Like so:
```
const db = new FakeFirestore({
  characters: [
    { id: 'homer', name: 'Homer', occupation: 'technician' },
    { id: 'krusty', name: 'Krusty', occupation: 'clown' },
    {
      id: 'bob',
      name: 'Bob',
      occupation: 'repairman',
      _subcollections: { // This will be skipped when generating the document data for 'bob'
        family: [
          { id: 'thing1', name: 'Thing 1', relation: 'pet' },
          { id: 'thing2', name: 'Thing 2', relation: 'pet' },
          { id: 'deborah', name: 'Deborah', relation: 'wife' },
        ],
      },
    },
  ],
});
```
Now for the fun part: how do we keep track of where we are in the object graph? Presently, everything is handled by an instance of `FakeFirestore`. Each call to `collection` sets a `collectionName` property and resets its `recordToFetch` property to `null`. Then when `doc` is called, the function looks in the mock database's root (`this.database[this.collectionName]`) for the document to pull.  It remembers that object until `collection` is called again!

Now, this works great when we have one or more references to documents at the root of the Firestore database, but this limits our view; we cannot dig any deeper.

In an effort to prevent many more persistent properties on `FakeFirestore`, and to permit multilevel retrieval in more places than one at a time, I recommend we refactor the `doc` and `collection` mocks to instead return reference objects.  These class instances would keep track of where they are in the tree by hanging onto a reference document, whose subcollections may be accessed via the `_subcollections` property defined on the mock database.

This change shouldn't break any existing behavior. It would be a wonderful improvement to the present one-layer-deep situation!  I'll start working on another PR for it 😊

**Comment by AverageHelper** [comment]
Another thought: If I'm reading the code right (it is getting late for me), it looks like a new instance of `FakeFirestore` is created each time we call `firestore()`.

This _would_ prevent us from overwriting our spot in the document tree, assuming first that `FakeFirestore` remains the main player in working with the document tree, and second that Firebase clients don't cache this object (say, as `db` or something) to access disperate parts of the tree between calls to `get`.  Unfortunately, we cannot prevent this, and it's actually a fairly common pattern to get several document references and call `get` on each of them in succession, such as in a batch or a transaction.

Unfortunately, I don't see a reliable way to juggle multiple paths down the document tree with just one referencing object.  We'll likely need to do what Firestore proper does and return something like `DocumentReference` and `CollectionReference` instances with each call to `doc` and `collection`, respectively.

Thoughts?

**Comment by MattGoldwater** [comment]
Are there any plans to incorporate sub-collection mocking? It would be really useful for me.

**Comment by AverageHelper** [comment]
@MattGoldwater  I've actually implemented something for that [in my own fork](https://github.com/AverageHelper/firestore-jest-mock).  I plan to take some time this weekend to bring it up to date with the master branch here and submit a PR.

**Comment by Shaggy13spe** [comment]
Maybe I'm missing something?? I have the following mocked db:
```
mockFirebase({
  database: {
    interviews: [
      {
        id: '1',
        recruit: 'John Doe',
        screener: 'Michael Morrison',
        email: 'jdoe@email.com',
        currentWhiteboard: {},
        interviewTimestamp: mockTimestamp,
        whiteboards: [{ ///this is a subcollection in actual Firestore
          id: '1',
          title: 'whiteboard1',
          scenario: 'scenario1',
          code: '',
        },
        {
          id: '2',
          title: 'whiteboard2',
          scenario: 'scenario2',
          code: '',
        }],
      },
]
```

this is the code for accessing the interview doc (and it's subcollection) and updating it:

```
  async addWhiteboard (interviewId, whiteboard) {
    const ref = this.firestore.db.collection('interviews').doc(interviewId).collection('whiteboards')

    await ref.doc(whiteboard.id).set(whiteboard)
  }
```
And my unit test:
```
  test('addWhiteboard', async () => {
    expect.assertions(5)
    const whiteboard = {
      id: '1',
      title: 'whiteboard1',
      scenario: 'scenario1',
      code: '',
    }
    const interviewService = new InterviewService()
    await interviewService.addWhiteboard('2', whiteboard)

    expect(mockCollection).toHaveBeenCalledWith('interviews')
    expect(mockDoc).toHaveBeenCalledWith('2')
    expect(mockCollection).toHaveBeenCalledWith('whiteboards')
    expect(mockDoc).toHaveBeenCalledWith('1')
    expect(mockSet).toHaveBeenCalledWith(whiteboard)
  })
```

This all works. Is there some other functionality that you are needing?

**Comment by AverageHelper** [comment]
@Shaggy13spe The issue is that that field is indistinguishable from a document field that contains an array of maps, each of which might have an `id` field. Our project had a few at the time that I opened this issue, and while there are certainly better ways to layout Firestore documents, sometimes you need to live with poor planning for a while 😅. Besides, since Firestore ([kindof](https://stackoverflow.com/q/49101373/3799856)) supports that case, we'd best be able to test that. My proposal is to [make the distinction more explicit](https://github.com/AverageHelper/firestore-jest-mock#subcollections) to better handle that case.

i.e. Since this ugly thing works, we should support it:
<img width="442" alt="Screen Shot 2020-09-12 at 9 34 56 AM" src="https://user-images.githubusercontent.com/1500092/92999076-5c31bc80-f4db-11ea-80d5-013a9c6bf7f9.png">

As a bonus, my fork restructures some things internally to cover [even more canon Firestore API](https://github.com/AverageHelper/firestore-jest-mock#functions-you-can-test) that [we just don't have right now](https://github.com/Upstatement/firestore-jest-mock#functions-you-can-test).

**Comment by Shaggy13spe** [comment]
Gotcha. I’m very new to this library, and it’s been very helpful so far. Looked over your PRs and will be excited to see them approved. Hopefully soon
