### ISSUE TITLE
Getting "FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created"

### ISSUE THREAD

**Issue by sfentress** [Upstatement/firestore-jest-mock#41]
# Description

From the readme it sounds like I should be able to do this:

```
import firebase from "firebase";
const { mockFirebase } = require("firestore-jest-mock");

describe("Database", () => {

  mockFirebase({
    database: {
      users: [
        { id: "abc123", name: "Homer Simpson" },
        { id: "abc456", name: "Lisa Simpson" },
      ],
      posts: [{ id: "123abc", title: "Really cool title" }],
    },
  });
  const db = firebase.firestore();

  it("can do something", () => {...});
});
```
However, the line `const db = firebase.firestore();` fails with `FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)`.

## Expected result

I should be able to initialize the DB.

## Environment

- Node version: 12.13.1
- Firebase version: 7.17.1
- firestore-jest-mock version: 0.5.0
- Running on macOS 10.15.2

**Comment by Shaggy13spe** [comment]
try using:
`const firebase = require('firebase')`
right before you declare initialize `const db`

That's what I'm doing and it works just fine. On another note, I'm using `import { mockFirebase } from 'firestore-jest-mock'. ;)

**Comment by FrozenKiwi** [comment]
I added the following from the help docs to get past that error:

```
  firebase.initializeApp({
    apiKey: '### FIREBASE API KEY ###',
    authDomain: '### FIREBASE AUTH DOMAIN ###',
    projectId: '### CLOUD FIRESTORE PROJECT ID ###'
  });
```

**Comment by FrozenKiwi** [comment]
see https://raw.githubusercontent.com/Upstatement/firestore-jest-mock/master/__tests__/full-setup.test.js

**Comment by sbatson5** [comment]
@sfentress are you still having any issues? If not, I will close this issue
