### ISSUE TITLE
Testing with FakeAuth not working: Cannot set property 'sendEmailVerification' of undefined

### ISSUE THREAD

**Issue by Shaggy13spe** [Upstatement/firestore-jest-mock#44]
# Description

Trying to test firebase.auth(), but getting an error. I've cloned this repo and the same tests seem to run just fine, but running in my actual code and using the npm package, it fails. Really not sure what it is I'm doing wrong, other than package versions, I'm following the same pattern as in this repo's tests, just inside my own solution. If this is not a defect, and something I'm doing wrong, I apologize for marking it as such.

## Steps to reproduce

```
test('signInUser', async () => {
    expect.assertions(1)
    mockFirebase({
      database: {
        users: [
          { id: 'abc123', name: 'Homer Simpson' },
          { id: 'abc456', name: 'Lisa Simpson' },
        ],
      },
    })
    const firebase = require('firebase')
    firebase.initializeApp(firebaseConfig)

    await firebase.auth().signInWithEmailAndPassword('sam', 'hill')
    expect(mockSignInWithEmailAndPassword).toHaveBeenCalledWith('sam', 'hill')
  })
```

## Expected result

The mock for signInWithEmailAndPassword should be called

## What happened.
```
TypeError: Cannot set property 'sendEmailVerification' of undefined

      35 |     firebase.initializeApp(firebaseConfig)
      36 | 
    > 37 |     await firebase.auth().signInWithEmailAndPassword('sam', 'hill')
         |                    ^
      38 |     expect(mockSignInWithEmailAndPassword).toHaveBeenCalledWith('sam', 'hill')
      39 |   })
      40 | })

      at new FakeAuth (node_modules/firestore-jest-mock/mocks/auth.js:10:39)
      at Object.auth (node_modules/firestore-jest-mock/mocks/firebase.js:14:14)
      at Object.<anonymous> (tests/unit/services/authorization/index.spec.js:37:20)
```

## Environment

- Node version: 12.14.1
"firebase": "^7.19.0",
"firebase-admin": "^9.1.1",
"firestore-jest-mock": "^0.5.0",
"jest": "^26.4.2",

**Comment by Shaggy13spe** [comment]
I seem to have found the issue. when installing the NPM package, it seems there is a bit of code missing that is currently in the master branch for the auth.js file.

###NPM Package: auth.js
```
class FakeAuth {
  constructor(currentUser) {
    currentUser.sendEmailVerification = mockSendVerificationEmail;
    this.currentUserRecord = currentUser;
  }
```

###Current master: auth.js
```
class FakeAuth {
  constructor(currentUser) {
    currentUser = currentUser || {};
    currentUser.sendEmailVerification = mockSendVerificationEmail;
    this.currentUserRecord = currentUser;
  }
```
I've uninstalled and reinstalled the npm package to make sure I in fact had the latest package version. I'm getting 0.5.0, which is what the master branch package.json lists as the version as well

**Comment by sbatson5** [comment]
🤔  if there is something missing, I will cut a new release (0.6.0)

**Comment by Shaggy13spe** [comment]
> 🤔 if there is something missing, I will cut a new release (0.6.0)

Thanks @sbatson5, currently I've altered my npm package locally to get around that, but of course that won't work when other developers do an npm install or during deployment.

**Comment by sbatson5** [comment]
0.6.0 is published:
https://www.npmjs.com/package/firestore-jest-mock

**Comment by sbatson5** [comment]
@Shaggy13spe I'm going to close as this issue is stale. Feel free to ping/re-open if this is still a problem
