### ISSUE TITLE
Github link on https://www.npmjs.com/package/firestore-jest-mock

### ISSUE THREAD

**Issue by seanburlington** [Upstatement/firestore-jest-mock#53]
# Summary

It would be helpful to have a github link on https://www.npmjs.com/package/firestore-jest-mock

## Motivation

I had a problem and wanted to checkout the source code 

But there was no link :-(

Fortunately you have released lots of code  \o/  and I was able to look at your other projects on npmjs, find your github page and then found the firebase code :-)

Maybe the missing link is a mistake ?

Thanks :-)

**Comment by sbatson5** [comment]
Thanks for pointing that out! Should be fixed in this PR: https://github.com/Upstatement/firestore-jest-mock/pull/54
