### ISSUE TITLE
Support @google-cloud/firestore

### ISSUE THREAD

**Issue by CorentinDoue** [Upstatement/firestore-jest-mock#71]
# Summary

[@google-cloud/firestore SDK](https://github.com/googleapis/nodejs-firestore) is an alternative to `firebase` and `firebase-admin` to interact with Firestore. The exported `Firestore` class is very similar (probably identical but Im not sure) to `firebase.firestore`.

## Basic example

I use `firestore-jest-mock` in one of my project with `@google-cloud/firestore`.
I added this file:
```ts
// firestore.mock
import { FakeFirestore } from 'firestore-jest-mock';

type Overrides = {
    database?: Record<string, unknown>;
};

const firestoreMock = (overrides: Overrides) => {
    class Firestore extends FakeFirestore {
        constructor() {
            super(overrides.database);
        }
    }
    return {
        FieldValue: FakeFirestore.FieldValue,
        Firestore,
    };
};

export const mockFirestore = (overrides = {}): void => {
    jest.doMock('@google-cloud/firestore', () => firestoreMock(overrides));
};
```
And I use `mockFirestore` exactly as the `mockFirebase` of `firestore-jest-mock`:
```ts
import { mockFirestore } from './firestore.mock';
import { mockCollection, mockDoc, mockSet } from 'firestore-jest-mock/mocks/firestore';

const getMockedFirestore = async () => {
    mockFirestore();
    const { Firestore } = await import('@google-cloud/firestore');
    return new Firestore({
        projectId: process.env.GCP_PROJECT_NAME,
    });
};

describe('restaurants', () => {
    it('creates the restaurant if it does not exist', async () => {
        const restaurantId = 15;
        const firestore = await getMockedFirestore();

        await firestore.collection('restaurants').doc(restaurantId.toString()).set({ restaurantId });

        expect(mockCollection).toHaveBeenCalledWith('restaurants');
        expect(mockDoc).toHaveBeenCalledWith(restaurantId.toString());
        expect(mockSet).toHaveBeenCalledWith({ restaurantId });
    });
});
```

## Motivation

 `firestore-jest-mock` provides a very useful means to test applications that use `Firestore`. The Firestore SDK is complicated to mock and the work done in `firestore-jest-mock` could also help the users of `@google-cloud/firestore` as well as the ones of `firebase`.

## Implementation

I propose a simple implementation to expose the `FakeFirestore` according to the signature of `@google-cloud/firestore` in the linked pull request.

**Comment by CorentinDoue** [comment]
The PR is merged, this will be included in the next release

**Comment by sbatson5** [comment]
Version `0.10.0` was released with these changes 👍
