### ISSUE TITLE
Batch Commit should return an array

### ISSUE THREAD

**Issue by HauptmannEck** [Upstatement/firestore-jest-mock#80]
# Summary

Currently the Batch Commit returns `undefined`, to not break systems that use the `WriteResult[]` response an array should be returned instead

## Basic example

```javascript
        const result = await batch.commit();
        logger.info( 'Records Saved:', result.length );
```
## Motivation

Without needing to mock the full `WriteResult` object an empty array would make sure things like `length`, `forEach` and `map` won't break.

## Proposed Change

```javascript
      commit() {
        mockBatchCommit(...arguments);
        return Promise.resolve([]);
      },
```

**Comment by sbatson5** [comment]
👍 Good call
