### ISSUE TITLE
docChanges() returns an object instead of an array

### ISSUE THREAD

**Issue by CorentinDoue** [Upstatement/firestore-jest-mock#89]
# Description

The method `docChanges` from `buildQuerySnapShot` 
https://github.com/Upstatement/firestore-jest-mock/blob/cc27ce8aea7549febca5d6ad726aa4403d478c2d/mocks/helpers/buildQuerySnapShot.js#L19

returns an object. 

But indeed this methods returns an array
https://github.com/googleapis/nodejs-firestore/blob/c7d67fb749aaf76050c08d29b4c6fca28ec9f5ce/types/firestore.d.ts#L1467
![Screenshot from 2021-04-20 16-27-48](https://user-images.githubusercontent.com/31917261/115414028-fd14f280-a1f5-11eb-9e46-82b9af4fefbc.png)

Consequently, my tests fail when using this method.

## Steps to reproduce

Try to test a code with usage of `docChanges` in a callback from `onSnapshot`.
Exemple: 
```ts
firestore()
    .collection(path)
    .onSnapshot(
      (querySnapshot) => {
        const updates = querySnapshot 
          .docChanges()
          .map((docChange) => ({
            ticket: docChange.doc.data(),
            type: docChange.type,
          }));
        storeApi.dispatch(updateStoredTickets(updates));
      },
    );
```

## Expected result

The test trigger no error 

## Actual result

Testing the code makes it crash

## Environment

- Ubuntu 20.04
- Node version: `14.15.5`

## Proposed fix

return an empty array

**Comment by sbatson5** [comment]
Thanks for bringing this up. The fix will be out in the next release
