### ISSUE TITLE
Bugs in Timestamp

### ISSUE THREAD

**Issue by karvaporo** [Upstatement/firestore-jest-mock#94]
I found some bugs.

1. https://github.com/Upstatement/firestore-jest-mock/blob/2d98d57050c7b8235b501c5c0effd6fa4111b500/mocks/timestamp.js#L30
Should be `d.setSeconds(this.seconds * 1000);`. Also, using `setSeconds()`, `setMilliseconds()` etc. comes with some problems - I'll get to this later.
2. https://github.com/Upstatement/firestore-jest-mock/blob/2d98d57050c7b8235b501c5c0effd6fa4111b500/mocks/timestamp.js#L32
Should use `d.getTime()` instead of `d.getMilliseconds()`.
3. https://github.com/Upstatement/firestore-jest-mock/blob/2d98d57050c7b8235b501c5c0effd6fa4111b500/mocks/timestamp.js#L42
This will cause the milliseconds to be added twice - once in the `nanoseconds` part and once as a fraction of the `seconds` part. It is not explicitly specified in the [documentation](https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp) but I think the intent is that both `seconds` and `nanoseconds` would be integers. The [implementation](https://github.com/firebase/firebase-js-sdk/blob/5ad33abe4c1987417b3df38a78de3e2ac1799d04/packages/firestore/src/lite/timestamp.ts#L70) from the actual Firebase SDK seems correct to me.
4. https://github.com/Upstatement/firestore-jest-mock/blob/2d98d57050c7b8235b501c5c0effd6fa4111b500/mocks/timestamp.js#L46-L50
This problem is a bit difficult to explain. But suppose you are currently at a time zone observing the DST (eg. Finland, May 2) then this will happen:
```
const now = new Date(); // now = Sun May 02 2021 21:12:49 GMT+0300 (EEST)
const nowFromMilliseconds = new Date(0); // nowFromMilliseconds = Thu Jan 01 1970 02:00:00 GMT+0200 (EET)
nowFromMilliseconds.setMilliseconds(now.getTime()); // nowFromMilliseconds = Sun May 02 2021 20:12:49 GMT+0300 (EEST)
```
As you can see, `nowFromMilliseconds` is trailing `now` by one hour. I've been reading the MDN Web Docs and language specs but I'm still not entirely clear about the mechanics of this. But I think the one hour discrepancy comes from the `nowFromMilliseconds` starting at a different time zone than where it's landing on when setting the milliseconds. Nevertheless, I think this headache could be prevented by just passing the milliseconds to the `Date` constructor and not setting milliseconds separately.

**Comment by karvaporo** [comment]
What I've done to fix this in our project is this:
```
      const stub = firebaseStub(mockFirebaseData, { includeIdsInData: true });
      const firebase = jest.requireActual('firebase');
      stub.firestore.Timestamp = firebase.firestore.Timestamp;
```
The `Timestamp` in Firebase SDK doesn't use any Firebase services so instead of reimplementing it in firestore-jest-mock it would be safe to just use the actual `Timestamp`.

**Comment by sbatson5** [comment]
This should be fixed in the latest release

**Comment by sbatson5** [comment]
@karvaporo is this still an issue in the latest release?

**Comment by karvaporo** [comment]
> @karvaporo is this still an issue in the latest release?

I'm on vacation at the moment so I have not actually tested yet but I went through #99 pretty thoroughly and from what I can see it should fix all of the above.
